### ISSUE TITLE
Add speech recognition support.

### ISSUE THREAD

**Issue by X3NOSIZ** [X3NOSIZ/IKYKWIS#1]
**Current Behavior**

Currently the app runs over native voice recognition threads. Add support for speech to text conversion support.

Also, 
- Increase the flow uptime to about 35%
- Follow proper [Contribution guidelines](https://github.com/X3NOSIZ/IKYKWIS/blob/main/.github/contributing.md)!

**Comment by Neilblaze** [comment]
Assign me this please! :zap:
